Upgrade to JoyPixels 6.5
shivangswain/JoyPixels pull request #1
Opened 2021-02-23 04:54 UTC by RainySummerLuo

2021-02-24 22:36 UTC, shivangswain commented on module.prop
> +author=shivangswain, RainySummer
I request you to remove your name from the author tag in the module.prop file. I'd rather add your name to the top of the README under a contributors section.

2021-02-24 22:36 UTC, shivangswain commented on README.md
> +5. Attribution not required.
Since this PR is for upgrading to JoyPixels 6.5, I'd request you to drop the README in this PR.

2021-02-24 22:37 UTC, shivangswain requested changes
Thank you so much for your valuable contribution. It is appreciated. I would request you to change the following to conform to standard practices:
- Please raise an issue before requesting a PR and linking the latter to the issue.
- We follow a policy of Atomic PRs (one PR, one concern). Since this PR is for upgrading to JoyPixels 6.5, I'd request you to drop the README in this PR.
- I request you to remove your name from the author tag in the module.prop file. I'd rather add your name to the top of the README under a contributor's section.

2021-02-25 00:38 UTC, RainySummerLuo commented
I've remove my name from **module.prop**, deleted the **README**, and created a issue related to this pull request.

Thank you!

2021-02-25 05:26 UTC, shivangswain reviewed
Looks great. Thank you for your contribution!

2021-02-25 05:30 UTC, merged